config/routes.rb
Rails.application.routes.draw do
  get 'events/new'

  root 'home#top'
  get '/about' => 'home#about'
  post '/events' => 'events#create'
  get '/events' => 'events#index'
  get '/events/:id' => 'events#show', as: 'event'
  get '/events/:id/edit' => 'events#edit', as: 'edit_event'
  patch '/events/:id' => 'events#update', as: 'update_event'
  delete '/events/:id' => 'events#destroy', as: 'destroy_event'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end

  def create
    @event = Event.new
    @event.title = params[:title]
    @event.content = params[:content]
    @event.place = params[:place]
    @event.save
    redirect_to event_path(@event.id)
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.title = params[:title]
    @event.content = params[:content]
    @event.place = params[:place]
    @event.save
    redirect_to event_path(@event.id)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @message = 'ようこそTECH_SALONへ！'
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/create.html.erb
<p><%= @event.title %></p>
<p><%= @event.content %></p>
<p><%= @event.place %></p>

app/views/events/edit.html.erb
<h1>勉強会情報を編集する</h1>
<%= form_tag update_event_path(@event.id), method: 'patch' do %>
<%= text_field_tag :tite, @event.title, class: "form-control title-field" %>
<%= text_area_tag :content, @event.content, class: "form-control content-field" %>
<%= text_field_tag :place, @event.place, class: "form-control title-field" %>
<%= submit_tag "保存", class: "btn primary-btn" %>
<% end %>

app/views/events/index.html.erb
<h1>勉強会の一覧</h1>
<ul class="events">
  <% @events.each do |event| %>
    <li>
      <p>タイトル</p>
      <span class="content">
        <%= link_to event.title, event_path(event.id) %>
      </span>
    </li>
  <% end %>

</ul>

app/views/events/new.html.erb
<h1>勉強会を作る</h1>

<%= form_tag events_path do %>

タイトル
<input name="title" type="text" class="form-control title-field">
内容
<textarea name="content" class="form-control content-field"></textarea>
場所
<input name="place" type="text" class="form-control title-field">

<input type="submit" value="作成" class="btn primary-btn">

<% end %>

app/views/events/show.html.erb
<h2>タイトル</h2>
<p><%= @event.title %></p>
<h2>内容</h2>
<p><%= @event.content %></p>
<h2>会場</h2>
<p><%= @event.place %></p>

<%= link_to '編集', edit_event_path(@event.id), class: 'btn edit-btn' %>
<%= link_to '削除', destroy_event_path(@event.id), method: 'delete',
class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>

app/views/home/about.html.erb
  <h1>TECH_SALONとは？</h1>
  <p>TECH_SALONとは◯◯◯なコミュニティです。</p>

app/views/home/top.html.erb
<h1><%= @message %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechSalon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container">
      <div id="logo">TECH_SALON</div>
      <ul class="header-right">
        <li><%= link_to 'Top', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'New', events_new_path %></li>
        <li><%= link_to 'Events', events_path %></li>
      </ul>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  <div class="container">
    <footer class="footer">
      <div class="small">
        &copy; 2016 TECH_SALON, Inc.
      </div>
    </footer>
  </div>

</body>
</html>